"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.setGlobalStructs = exports.pluralize = exports.getRedisClient = exports.getModels = exports.getIncludeAliasesByOrderPrefixes = exports.env = exports.connectToAMQP = void 0;
const connect_to_amqp_1 = __importDefault(require("./lib/connect-to-amqp"));
exports.connectToAMQP = connect_to_amqp_1.default;
const env_1 = __importDefault(require("./lib/env"));
exports.env = env_1.default;
const get_include_aliases_by_order_prefixes_1 = __importDefault(require("./lib/get-include-aliases-by-order-prefixes"));
exports.getIncludeAliasesByOrderPrefixes = get_include_aliases_by_order_prefixes_1.default;
const get_models_1 = __importDefault(require("./lib/get-models"));
exports.getModels = get_models_1.default;
const get_redis_client_1 = __importDefault(require("./lib/get-redis-client"));
exports.getRedisClient = get_redis_client_1.default;
const pluralize_1 = __importDefault(require("./lib/pluralize"));
exports.pluralize = pluralize_1.default;
const set_global_structs_1 = __importDefault(require("./lib/set-global-structs"));
exports.setGlobalStructs = set_global_structs_1.default;
